<?php
// $Id: invite_cancel_account.module,v 1.3 2008/08/20 13:26:12 smk Exp $

/**
 * @file
 * Allows your users to terminate user accounts by withdrawing their
 * invitation.
 */

/**
 * Implementation of hook_invite().
 *
 * Withdrawing an invitation leads to termination of invited user's account.
 */
function invite_cancel_account_invite($op, $invite, &$roles = NULL) {
  switch ($op) {
    case 'cancel':
      if (user_access('withdraw accepted invitations') && $invite->invitee) {
        user_delete(array(), $invite->invitee->uid);
        drupal_set_message(t('Deleted user: %name', array('%name' => $invite->invitee->name)));
      }
      break;
  }
}
